#!/usr/bin/env python3
"""Assign the lightweight Zensical template to generated by-id records.

Generated pages are intentionally ignored by Git, so template metadata must be
applied on every build after all generators have finished and before Zensical
renders the site.
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = "data-record.html"


@dataclass(frozen=True)
class RecordSet:
    label: str
    relative_dir: str
    minimum: int


RECORD_SETS: tuple[RecordSet, ...] = (
    RecordSet("Unit", "data/units/by-id", 4_000),
    RecordSet("Magic Site", "data/sites/by-id", 1_200),
    RecordSet("Magic Item", "data/items/by-id", 500),
)


def front_matter_end(lines: list[str], path: Path) -> int:
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"generated record has no front matter: {path}")
    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return index
    raise ValueError(f"generated record has unclosed front matter: {path}")


def apply_template(path: Path, template: str = TEMPLATE) -> bool:
    """Apply one template metadata key and return whether the file changed."""

    text = path.read_text(encoding="utf-8")
    keep_newline = text.endswith("\n")
    lines = text.splitlines()
    end = front_matter_end(lines, path)
    metadata = lines[1:end]

    if not any(line.strip() == "status: generated" for line in metadata):
        raise ValueError(f"by-id record is not marked as generated: {path}")

    template_indexes = [
        index
        for index, line in enumerate(metadata, start=1)
        if line.lstrip().startswith("template:")
    ]
    expected = f'template: "{template}"'
    if template_indexes:
        if len(template_indexes) != 1:
            raise ValueError(f"generated record has duplicate template metadata: {path}")
        current = lines[template_indexes[0]].split(":", 1)[1].strip().strip("\"'")
        if current != template:
            raise ValueError(
                f"generated record already uses another template: {path}: {current}"
            )
        return False

    # Keep title first, then make rendering behavior visible near the top of the
    # metadata block. This remains valid for all existing generated front matter.
    insert_at = 2 if end >= 2 and lines[1].lstrip().startswith("title:") else 1
    lines.insert(insert_at, expected)
    output = "\n".join(lines) + ("\n" if keep_newline else "")
    path.write_text(output, encoding="utf-8")
    return True


def apply_templates(
    docs_dir: Path,
    record_sets: Iterable[RecordSet] = RECORD_SETS,
) -> dict[str, dict[str, int]]:
    """Apply the template to every configured generated record set."""

    docs_dir = docs_dir.resolve()
    results: dict[str, dict[str, int]] = {}
    for record_set in record_sets:
        directory = docs_dir / record_set.relative_dir
        if not directory.is_dir():
            raise FileNotFoundError(f"generated record directory does not exist: {directory}")
        files = sorted(directory.glob("*.md"))
        if len(files) < record_set.minimum:
            raise ValueError(
                f"{record_set.label} record set appears incomplete: "
                f"{len(files)} < {record_set.minimum}"
            )
        changed = sum(apply_template(path) for path in files)
        results[record_set.label] = {"records": len(files), "changed": changed}
    return results


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="生成済みUnit・Magic Site・Magic Item個別ページへ軽量Templateを設定します。"
    )
    parser.add_argument("--docs-dir", type=Path, default=ROOT / "docs")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        results = apply_templates(args.docs_dir)
    except (OSError, ValueError) as exc:
        print(f"ERROR: data-record template assignment failed: {exc}")
        return 1

    for label, stats in results.items():
        print(f"{label}: records={stats['records']} changed={stats['changed']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
